FROM node:20-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package.json ./
RUN npm install

COPY entrypoint.dev.sh ./
RUN chmod +x entrypoint.dev.sh

EXPOSE 3000

ENTRYPOINT ["./entrypoint.dev.sh"]
